### ISSUE TITLE
Does not work in MacOS Catalina 10.15.1

### ISSUE THREAD

**Issue by andgineer** [nielsAD/travis-lazarus#23]
`TRAVIS_OS_NAME=osx python3 .travis.install.py`

`Error: caskroom/cask was moved. Tap homebrew/cask-cask instead.`

**Comment by GerryFerdinandus** [comment]
@andgineer 

This issue is already fix (but not yet merge):
https://github.com/nielsAD/travis-lazarus/pull/22
You can check my experimental fork if you want to copy some other related fixed to your own copy.
https://github.com/GerryFerdinandus/travis-lazarus
Warning: No support from me for this experimental fork.
Some changes are:
- python 2 -> 3
- Add GUI test program to check if xvfb work.
- modify the DoTestRun() function

I use this fork for my own project 
https://github.com/GerryFerdinandus/bittorrent-tracker-editor
